# Use the official httpd image with Alpine Linux as base
FROM httpd:alpine

# Copy the contents of project-1 directory to Apache document root
COPY ./ /usr/local/apache2/htdocs/

# Expose port 80
EXPOSE 80

CMD ["httpd-foreground"]


